/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 public/eth.gltf -ts
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001_Plane002: THREE.Mesh
    Plane_Plane001: THREE.Mesh
  }
  materials: {
    stone: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/eth.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane001_Plane002.geometry} material={materials.stone} rotation={[Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane_Plane001.geometry} material={materials.stone} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/eth.gltf')
