import Head from "next/head"

export default function Home() {
	return (
		<>
			<Head>
				<title>Archive.com</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
			</Head>
			<div
				id="home-wrapper"
				style={{
					position: "fixed",
					top: "13vh",
					left: "0",
					right: "0",
					bottom: "0",
					zIndex: -1,
					background: "linear-gradient(to right, #DECBA4, #3E5151)",
				}}
			>
				hello
			</div>
		</>
	)
}
